INT-355_test_iq_server_dockerfile
sonatype/docker-nexus-iq-server pull request #2
Opened 2017-09-25 06:55 UTC by fernau

JIRA: https://issues.sonatype.org/browse/INT-355

I would prefer serverspec.org for testing docker images. It is essentially the same what we do for chef, but I found kitchen not to work very well with docker.

- serverspec does not need SSH in the docker container
- serverspec does not hijack the 'CMD' command to run its tests
- serverspec runs the tests inside the container

2017-09-28 21:11 UTC, whyjustin requested changes

2017-09-28 21:11 UTC, whyjustin commented on spec/Dockerfile_spec.rb
> +# spec/Dockerfile_spec.rb
License header

2017-09-28 21:11 UTC, whyjustin commented on spec/Dockerfile_spec.rb
> +    solo = JSON.parse(File.read('/var/chef/solo.json'))
Single or double quotes consistently

2017-09-28 21:11 UTC, whyjustin commented on spec/Dockerfile_spec.rb
> +    expect(process('java')[:user]).to eq('nexus')
Can we verify more with the process args? Or just the user?

2017-09-29 15:09 UTC, fernau commented on spec/Dockerfile_spec.rb
> +    expect(process('java')[:user]).to eq('nexus')
we can verify most things with process. here is the link: http://serverspec.org/resource_types.html#process

2017-09-29 15:34 UTC, fernau commented on spec/Dockerfile_spec.rb
> +# spec/Dockerfile_spec.rb
added license header in 0007ead

2017-09-29 15:35 UTC, fernau commented on spec/Dockerfile_spec.rb
> +    solo = JSON.parse(File.read('/var/chef/solo.json'))
fixed inconsistent use of quotes in 0007ead

2017-09-30 01:47 UTC, bigspotteddog commented on spec/Dockerfile_spec.rb
> +    solo = JSON.parse(File.read('/var/chef/solo.json'))
This file will not exist when after the cleanup happens. I added a change in #3 to address this.

2017-10-02 14:48 UTC, bigspotteddog approved these changes

2017-10-06 23:33 UTC, whyjustin approved these changes

2017-10-20 12:51 UTC, merged