Add a Jenkinsfile to build, test, and tag the Dockerfile
sonatype/docker-nexus-iq-server pull request #4
Opened 2017-10-13 02:21 UTC by bigspotteddog

https://issues.sonatype.org/browse/INT-352
https://jenkins.zion.aws.s/job/integrations/job/docker-nexus-iq-server-feature/job/INT-332_jenkins_build_and_tag

2017-10-13 02:34 UTC, bigspotteddog commented on Jenkinsfile
> +    if (line.startsWith('ENV IQ_SERVER_COOKBOOK_VERSION="release-')) {
Need a better way to determine the version for this release. Semantic? Or, the nexus-iq-server release as sonatype-nexus3 is done?

2017-10-13 14:23 UTC, bigspotteddog commented on Jenkinsfile
> +    if (line.startsWith('ENV IQ_SERVER_COOKBOOK_VERSION="release-')) {
Used the IQ_SERVER_VERSION version that is now set in the Dockerfile (89d8567).

2017-10-13 15:52 UTC, fernau commented on Jenkinsfile
> +      withEnv(["PATH+GEMS=${gemInstallDirectory}/bin"]) {
/

2017-10-13 15:54 UTC, fernau approved these changes
+1

2017-10-13 15:54 UTC, fernau commented on Dockerfile
> +ENV IQ_SERVER_SHA256=a1a5d127e2deaf2b26ed4e605802986b99ea317c8a821059c918783517728d6c
are these parameters now mandatory or is this just for testing ?

2017-10-13 16:00 UTC, bigspotteddog commented on Dockerfile
> +ENV IQ_SERVER_SHA256=a1a5d127e2deaf2b26ed4e605802986b99ea317c8a821059c918783517728d6c
I was thinking these would be mandatory tagging purposes, similar to how the Nexus Repository Manager docker image is done.

Another idea would be for the chef recipe to somehow communicate the version it is building; maybe writing to a file.

2017-10-13 16:29 UTC, fernau commented on Dockerfile
> +ENV IQ_SERVER_SHA256=a1a5d127e2deaf2b26ed4e605802986b99ea317c8a821059c918783517728d6c
no it's better to leave it as it is was just asking. thanks

2017-10-13 22:19 UTC, whyjustin requested changes
Some feedback - needs change to push to Docker Hub as well.

2017-10-13 22:19 UTC, whyjustin commented on Jenkinsfile
> +      gitHubUsername = 'sonatype'
This is an organization, not a user

2017-10-13 22:19 UTC, whyjustin commented on Jenkinsfile
> +      gitHubUsername = 'sonatype'
These can be declared when they are defined.

2017-10-13 22:19 UTC, whyjustin commented on Jenkinsfile
> +      buildType = scm.branches[0].name != '*/master' ? 'snapshot' : 'release'
This isn't used

2017-10-13 22:19 UTC, whyjustin commented on Jenkinsfile
> +        OsTools.runSafe(this, "rspec --backtrace spec/Dockerfile_spec.rb")
We should build the image in a separate stage and then test the built image, separating the build from the testing.

2017-10-13 22:19 UTC, whyjustin commented on Jenkinsfile
> +    if (currentBuild.result == 'FAILURE') {
We don't need to archive on failure

2017-10-14 01:41 UTC, bigspotteddog commented on Jenkinsfile
> +      gitHubUsername = 'sonatype'
Declared when defined (429c642).

2017-10-14 01:41 UTC, bigspotteddog commented on Jenkinsfile
> +    if (currentBuild.result == 'FAILURE') {
Moved the archive below the failure check (429c642).

2017-10-14 01:42 UTC, bigspotteddog commented on Jenkinsfile
> +      buildType = scm.branches[0].name != '*/master' ? 'snapshot' : 'release'
Removed this (429c642).

2017-10-14 01:42 UTC, bigspotteddog commented
Applied the same comments to https://github.com/sonatype/docker-nexus3/pull/81.

2017-10-14 16:30 UTC, bigspotteddog commented on Jenkinsfile
> +        OsTools.runSafe(this, "rspec --backtrace spec/Dockerfile_spec.rb")
Build first, then test (ba15074).

2017-10-19 00:17 UTC, whyjustin approved these changes

2017-10-21 01:09 UTC, merged