INT - Document Nexus IQ Server configuration
sonatype/docker-nexus-iq-server pull request #9
Opened 2017-11-02 22:15 UTC by bigspotteddog

Add documentation for configuring Nexus IQ Server through the solo.json.erb template.

2017-11-02 22:54 UTC, whyjustin commented on README.md
> +The solo.json.erb template file can be used to customize the Nexus IQ Server configuration. Here is a fully expanded
IIUC these are just the fields that we specify in default.rb. I believe anything that's set under ['nexus_iq_server']['config'] is marshaled to yml. @fernau could confirm

2017-11-02 22:54 UTC, whyjustin commented on README.md
> +    :config => {
I think the most important thing to doc is that anything under config will become config.yml and it supports everything that the IQ Server supports [0]

[0] https://help.sonatype.com/display/NXIQ/IQ+Server+Configuration

2017-11-02 23:10 UTC, bigspotteddog commented on README.md
> +The solo.json.erb template file can be used to customize the Nexus IQ Server configuration. Here is a fully expanded
Yes, you are correct. Anything under config is added to config.yml.

2017-11-02 23:12 UTC, bigspotteddog commented on README.md
> +    :config => {
Referred the reader to the IQ Server Configuration section of Sonatype Help for more details. Used the solo.json.erb snippet as an example mentioning that the values are the defaults from the cookbook (6e1091f).

2017-11-02 23:50 UTC, whyjustin requested changes

2017-11-02 23:50 UTC, whyjustin commented on README.md
> +The `solo.json.erb` template file can be used to customize the Nexus IQ Server configuration. Any attribute values added
"Any attribute values..."

This sentence is pretty confusing to me. How about something like:

```
"The `nexus_iq_server.config` property of this Embedded Ruby template will be rendered and then saved as the Nexus IQ Server's config.yml. See
 +[IQ Server Configuration](https://help.sonatype.com/display/NXIQ/IQ+Server+Configuration) for more details as to what values are supported.
```

Part of the difficulty is we are going ERB -> JSON -> YML which leads to confusion.

2017-11-02 23:50 UTC, whyjustin commented on README.md
> +    :version => '1.39.0-04',
This is the second time a version number has shown up in the docs. This will date itself quickly, I suggest omitting versions and using the `ENV[]` variables.

2017-11-02 23:50 UTC, whyjustin commented on README.md
> +    :logs_dir => '/var/log/nexus-iq-server',
This is quite long. How about omitting logs, conf_dir and only showing how to change one property of config. i.e. "Here is an example of how to set the proxy section of config.yml."

2017-11-03 00:22 UTC, bigspotteddog commented on README.md
> +The `solo.json.erb` template file can be used to customize the Nexus IQ Server configuration. Any attribute values added
Thanks for the sentence. Used this (612c31e).

2017-11-03 00:22 UTC, bigspotteddog commented on README.md
> +    :version => '1.39.0-04',
Changed back to ENV[] variables (612c31e).

2017-11-03 00:22 UTC, bigspotteddog commented on README.md
> +    :logs_dir => '/var/log/nexus-iq-server',
Great suggestion! Done (612c31e).

2017-11-03 15:19 UTC, whyjustin approved these changes

2017-11-06 19:34 UTC, merged